[package]
name = "video_schedule"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros", "time", "net"] }
serde_json = "1.0.133"
serde = { version = "1.0.215", features = ["derive"] }