[package]
name = "video_schedule"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
winapi = { version = "0.3.9", features = ["namedpipeapi", "winuser"] }
anyhow = "1.0"
